# Form implementation generated from reading ui file 'ProductDetail.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProductDetail(object):
    def setupUi(self, ProductDetail):
        ProductDetail.setObjectName("ProductDetail")
        ProductDetail.resize(1164, 738)
        font = QtGui.QFont()
        font.setPointSize(13)
        ProductDetail.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=ProductDetail)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 30, 1161, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.productName = QtWidgets.QLabel(parent=self.frame)
        self.productName.setGeometry(QtCore.QRect(0, -1, 1161, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.productName.setFont(font)
        self.productName.setText("")
        self.productName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.productName.setObjectName("productName")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(60, 109, 461, 481))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.productID = QtWidgets.QLabel(parent=self.frame_2)
        self.productID.setText("")
        self.productID.setObjectName("productID")
        self.gridLayout.addWidget(self.productID, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.warrantyTime = QtWidgets.QLabel(parent=self.frame_2)
        self.warrantyTime.setText("")
        self.warrantyTime.setObjectName("warrantyTime")
        self.gridLayout.addWidget(self.warrantyTime, 4, 1, 1, 1)
        self.supplierName = QtWidgets.QLabel(parent=self.frame_2)
        self.supplierName.setText("")
        self.supplierName.setObjectName("supplierName")
        self.gridLayout.addWidget(self.supplierName, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.type = QtWidgets.QLabel(parent=self.frame_2)
        self.type.setText("")
        self.type.setObjectName("type")
        self.gridLayout.addWidget(self.type, 2, 1, 1, 1)
        self.price = QtWidgets.QLabel(parent=self.frame_2)
        self.price.setText("")
        self.price.setObjectName("price")
        self.gridLayout.addWidget(self.price, 5, 1, 1, 1)
        self.back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back.setGeometry(QtCore.QRect(1000, 620, 91, 41))
        self.back.setObjectName("back")
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(600, 110, 501, 481))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.detail = QtWidgets.QTextBrowser(parent=self.frame_3)
        self.detail.setGeometry(QtCore.QRect(-5, 1, 511, 481))
        self.detail.setStyleSheet("#detail {\n"
"background-color: rgba(255, 255, 255, 0.000001);}")
        self.detail.setObjectName("detail")
        ProductDetail.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ProductDetail)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1164, 26))
        self.menubar.setObjectName("menubar")
        ProductDetail.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ProductDetail)
        self.statusbar.setObjectName("statusbar")
        ProductDetail.setStatusBar(self.statusbar)

        self.retranslateUi(ProductDetail)
        QtCore.QMetaObject.connectSlotsByName(ProductDetail)

    def retranslateUi(self, ProductDetail):
        _translate = QtCore.QCoreApplication.translate
        ProductDetail.setWindowTitle(_translate("ProductDetail", "MainWindow"))
        self.label_7.setText(_translate("ProductDetail", "Price:"))
        self.label_2.setText(_translate("ProductDetail", "ProductID:"))
        self.label_3.setText(_translate("ProductDetail", "Type:"))
        self.label_6.setText(_translate("ProductDetail", "Warranty time:"))
        self.label_8.setText(_translate("ProductDetail", "Supplier name:"))
        self.back.setText(_translate("ProductDetail", "Back"))
        self.detail.setHtml(_translate("ProductDetail", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProductDetail = QtWidgets.QMainWindow()
    ui = Ui_ProductDetail()
    ui.setupUi(ProductDetail)
    ProductDetail.show()
    sys.exit(app.exec())
