# Form implementation generated from reading ui file 'SignIn.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SignIn(object):
    def setupUi(self, SignIn):
        SignIn.setObjectName("SignIn")
        SignIn.resize(1164, 736)
        font = QtGui.QFont()
        font.setPointSize(13)
        SignIn.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=SignIn)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(9, 60, 1151, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 1151, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(369, 170, 451, 211))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.username = QtWidgets.QLineEdit(parent=self.frame_2)
        self.username.setObjectName("username")
        self.gridLayout.addWidget(self.username, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.password = QtWidgets.QLineEdit(parent=self.frame_2)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 1, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(370, 470, 451, 91))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.signIn = QtWidgets.QPushButton(parent=self.frame_3)
        self.signIn.setGeometry(QtCore.QRect(10, 20, 121, 41))
        self.signIn.setObjectName("signIn")
        self.signUp = QtWidgets.QPushButton(parent=self.frame_3)
        self.signUp.setGeometry(QtCore.QRect(320, 20, 121, 41))
        self.signUp.setObjectName("signUp")
        self.massage = QtWidgets.QLabel(parent=self.centralwidget)
        self.massage.setGeometry(QtCore.QRect(370, 410, 451, 31))
        self.massage.setText("")
        self.massage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.massage.setObjectName("massage")
        SignIn.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=SignIn)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1164, 26))
        self.menubar.setObjectName("menubar")
        SignIn.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=SignIn)
        self.statusbar.setObjectName("statusbar")
        SignIn.setStatusBar(self.statusbar)

        self.retranslateUi(SignIn)
        QtCore.QMetaObject.connectSlotsByName(SignIn)

    def retranslateUi(self, SignIn):
        _translate = QtCore.QCoreApplication.translate
        SignIn.setWindowTitle(_translate("SignIn", "MainWindow"))
        self.label.setText(_translate("SignIn", "Sign in"))
        self.label_3.setText(_translate("SignIn", "Password"))
        self.label_2.setText(_translate("SignIn", "Username"))
        self.signIn.setText(_translate("SignIn", "Sign in"))
        self.signUp.setText(_translate("SignIn", "Sign up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignIn = QtWidgets.QMainWindow()
    ui = Ui_SignIn()
    ui.setupUi(SignIn)
    SignIn.show()
    sys.exit(app.exec())
